const C=window.FUTUREPATH_CONFIG||{};
const ready=C.supabaseUrl&&C.supabasePublishableKey&&!C.supabasePublishableKey.includes("PASTE_YOUR");
const db=ready?supabase.createClient(C.supabaseUrl,C.supabasePublishableKey):null;
const subjects={Maths:["Algebra","Geometry","Ratio and proportion","Statistics"],"English Language":["Reading skills","Writing skills","Language analysis","Spelling and punctuation"],Biology:["Cells","Organisation","Bioenergetics","Ecology"],Chemistry:["Atomic structure","Bonding","Quantitative chemistry","Chemical changes"],Physics:["Energy","Electricity","Forces","Waves"],"Computer Science":["Algorithms","Programming","Data representation","Cyber security"],Geography:["Natural hazards","Urban issues","Physical landscapes","Resource management"],History:["Conflict","Power and the people","Migration","Elizabethan England"]};
const careers=[
["software-engineer","Software Engineer",["Maths","Computer Science"],["Problem solving","Programming"],"Design, build and improve software."],
["doctor","Doctor",["Biology","Chemistry"],["Science","Communication"],"Diagnose and treat illness as part of a healthcare team."],
["architect","Architect",["Maths","Physics","Art"],["Design","Planning"],"Design buildings and spaces using creative and technical thinking."],
["engineer","Engineer",["Maths","Physics","Computer Science"],["Design","Problem solving"],"Use maths and science to design and improve real-world systems."],
["teacher","Teacher",["English Language","Maths","History"],["Communication","Leadership"],"Help students learn, build confidence and understand ideas."],
["cyber-security","Cyber Security Analyst",["Computer Science","Maths"],["Security","Analysis"],"Help organisations protect networks and information."],
["vet","Veterinary Surgeon",["Biology","Chemistry"],["Science","Animal care"],"Care for animals and investigate health problems."],
["graphic-designer","Graphic Designer",["Art","Computer Science","English Language"],["Creativity","Visual design"],"Create visual ideas for brands and digital media."],
["environmental-scientist","Environmental Scientist",["Biology","Chemistry","Geography"],["Research","Sustainability"],"Study environmental problems and develop sustainable solutions."],
["journalist","Journalist",["English Language","History"],["Writing","Research"],"Research stories and communicate information clearly."],
["accountant","Accountant",["Maths","Computer Science"],["Numbers","Organisation"],"Use financial information to support decisions."],
["paramedic","Paramedic",["Biology","Chemistry"],["Teamwork","Decision-making"],"Provide emergency medical care and support patients."]
].map(x=>({id:x[0],name:x[1],subjects:x[2],skills:x[3],desc:x[4]}));
const ach=[["first-topic","📚","First Steps","Complete your first revision topic.",20],["five-topics","🔥","Revision Streak","Complete five revision topics.",40],["first-career","💼","Career Explorer","Save your first career.",20],["three-careers","🧭","Career Planner","Save three careers.",40],["level-two","⭐","Level Up","Reach level 2.",50]];
let user=null,profile={display_name:"Student",xp:0,level:1},rows=[],saved=[],unlocked=[],mode="login";
const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function toast(s){let x=$("toast");x.textContent=s;x.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>x.classList.remove("show"),2300)}
function page(p){if(!user)p="auth";document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$(`${p}Page`).classList.remove("hidden");location.hash=p;if(p==="dashboard")dashboard();if(p==="revision")revision();if(p==="careers")renderCareers();if(p==="progress")progress()}
function level(x){return Math.floor(x/100)+1}
async function load(){let [p,r,c,a]=await Promise.all([db.from("profiles").select("*").eq("id",user.id).maybeSingle(),db.from("revision_progress").select("*").eq("user_id",user.id),db.from("saved_careers").select("career_id").eq("user_id",user.id),db.from("achievements").select("achievement_id").eq("user_id",user.id)]);if(p.error||r.error||c.error||a.error)throw(p.error||r.error||c.error||a.error);if(!p.data){let z=await db.from("profiles").insert({id:user.id,display_name:user.user_metadata?.display_name||user.email.split("@")[0],xp:0,level:1}).select().single();if(z.error)throw z.error;profile=z.data}else profile=p.data;rows=r.data||[];saved=(c.data||[]).map(x=>x.career_id);unlocked=(a.data||[]).map(x=>x.achievement_id)}
async function xp(n){let oldLevel=profile.level,x=profile.xp+n,l=level(x);let r=await db.from("profiles").update({xp:x,level:l,updated_at:new Date().toISOString()}).eq("id",user.id).select().single();if(r.error)throw r.error;profile=r.data;toast(l>oldLevel?`⭐ Level ${l}!`:`+${n} XP`)}
async function unlock(id){if(unlocked.includes(id))return;let a=ach.find(x=>x[0]===id);let r=await db.from("achievements").insert({user_id:user.id,achievement_id:id});if(r.error&&r.error.code!=="23505")throw r.error;unlocked.push(id);if(a){await xp(a[4]);toast(`${a[1]} ${a[2]} unlocked`)}}
async function achievements(){let n=rows.filter(x=>x.completed).length;if(n>=1)await unlock("first-topic");if(n>=5)await unlock("five-topics");if(saved.length>=1)await unlock("first-career");if(saved.length>=3)await unlock("three-careers");if(profile.level>=2)await unlock("level-two")}
async function topic(s,t,v){let old=rows.find(x=>x.subject===s&&x.topic===t)?.completed;let r=await db.from("revision_progress").upsert({user_id:user.id,subject:s,topic:t,completed:v,score:v?100:0,updated_at:new Date().toISOString()});if(r.error)return toast(r.error.message);let row=rows.find(x=>x.subject===s&&x.topic===t);if(row)row.completed=v;else rows.push({subject:s,topic:t,completed:v});if(v&&!old)await xp(10);revision();dashboard();await achievements()}
async function career(id){let has=saved.includes(id);let r=has?await db.from("saved_careers").delete().eq("user_id",user.id).eq("career_id",id):await db.from("saved_careers").insert({user_id:user.id,career_id:id});if(r.error)return toast(r.error.message);if(has)saved=saved.filter(x=>x!==id);else{saved.push(id);await xp(5)}renderCareers();progress();dashboard();await achievements()}
function dashboard(){$("welcomeName").textContent=profile.display_name||"student";$("level").textContent=profile.level;$("xp").textContent=profile.xp;$("revisionCount").textContent=rows.filter(x=>x.completed).length;$("careerCount").textContent=saved.length;$("achievementCount").textContent=unlocked.length;$("nextLevel").textContent=Math.max(0,profile.level*100-profile.xp);let d=rows.filter(x=>x.completed).slice(-4).reverse();$("dashTopics").innerHTML=d.map(x=>`<div class="item"><div><b>${esc(x.subject)}</b><small>${esc(x.topic)}</small></div>✓</div>`).join("")||`<div class="item">No completed topics yet.</div>`;let cs=careers.filter(x=>saved.includes(x.id));$("dashCareers").innerHTML=cs.map(x=>`<div class="item"><div><b>${esc(x.name)}</b><small>${esc(x.subjects.join(" • "))}</small></div><button class="link" data-open="${x.id}">Open</button></div>`).join("")||`<div class="item">No saved careers yet.</div>`}
function revision(){$("revisionGrid").innerHTML=Object.entries(subjects).map(([s,ts])=>`<article class="subject"><h2>${esc(s)}</h2>${ts.map(t=>{let r=rows.find(x=>x.subject===s&&x.topic===t);return`<div class="topic"><input type="checkbox" data-s="${esc(s)}" data-t="${esc(t)}" ${r?.completed?"checked":""}><label>${esc(t)}</label></div>`}).join("")}</article>`).join("")}
function renderCareers(){let q=$("search").value.toLowerCase();let cs=careers.filter(c=>[c.name,c.desc,...c.subjects,...c.skills].join(" ").toLowerCase().includes(q));$("careerGrid").innerHTML=cs.map(c=>`<article class="career"><h3>${esc(c.name)}</h3><div class="chips">${c.subjects.map(s=>`<span class="chip">${esc(s)}</span>`).join("")}</div><p>${esc(c.desc)}</p><div class="actions"><button class="secondary" data-open="${c.id}">View</button><button class="${saved.includes(c.id)?"secondary":"primary"}" data-save="${c.id}">${saved.includes(c.id)?"Saved ✓":"Save"}</button></div></article>`).join("")}
function progress(){$("progressXP").textContent=profile.xp;$("progressLevel").textContent=profile.level;$("xpBar").style.width=(profile.xp%100)+"%";$("achievements").innerHTML=ach.map(a=>`<div class="achievement ${unlocked.includes(a[0])?"unlocked":""}">${a[1]} <strong>${esc(a[2])}</strong><small>${esc(a[3])} ${unlocked.includes(a[0])?"✓":"🔒"}</small></div>`).join("");$("savedCareers").innerHTML=careers.filter(c=>saved.includes(c.id)).map(c=>`<div class="item"><div><b>${esc(c.name)}</b><small>${esc(c.subjects.join(" • "))}</small></div><button class="link" data-open="${c.id}">Open</button></div>`).join("")||`<div class="item">No saved careers yet.</div>`}
function openCareer(id){let c=careers.find(x=>x.id===id);$("dialogTitle").textContent=c.name;$("dialogBody").innerHTML=`<p>${esc(c.desc)}</p><h3>Useful subjects</h3><div class="chips">${c.subjects.map(x=>`<span class="chip">${esc(x)}</span>`).join("")}</div><h3>Useful skills</h3><div class="chips">${c.skills.map(x=>`<span class="chip">${esc(x)}</span>`).join("")}</div>`;$("careerDialog").showModal()}
function msg(s){$("authMessage").textContent=s}
async function auth(e){e.preventDefault();if(!db)return msg("Add your Supabase publishable key to config.js first.");let email=$("email").value.trim(),password=$("password").value;try{let r;if(mode==="signup"){r=await db.auth.signUp({email,password,options:{data:{display_name:$("displayName").value.trim()||email.split("@")[0]}}});if(r.error)throw r.error;if(!r.data.session)return msg("Account created. Check your email to confirm it, then log in.")}else{r=await db.auth.signInWithPassword({email,password});if(r.error)throw r.error}user=r.data.user;await load();$("accountLabel").textContent=profile.display_name||user.email; $("authButton").textContent="Log out";page("dashboard")}catch(e){msg(e.message)}}
async function logout(){if(db)await db.auth.signOut();user=null;rows=[];saved=[];unlocked=[];profile={display_name:"Student",xp:0,level:1};$("accountLabel").textContent="Not signed in";$("authButton").textContent="Sign in";page("auth")}
$("authForm").addEventListener("submit",auth);$("forgot").onclick=async()=>{if(!db)return msg("Add your publishable key first.");let e=$("email").value.trim();if(!e)return msg("Enter your email first.");let r=await db.auth.resetPasswordForEmail(e,{redirectTo:location.href});msg(r.error?r.error.message:"If that account exists, a reset email has been sent.")};
document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.mode===mode));$("nameWrap").classList.toggle("hidden",mode!=="signup");$("authSubmit").textContent=mode==="signup"?"Create account":"Log in";$("authTitle").textContent=mode==="signup"?"Create your FuturePath account":"Welcome back"});
$("search").oninput=renderCareers;$("closeDialog").onclick=()=>$("careerDialog").close();
document.addEventListener("click",e=>{let p=e.target.closest("[data-page]");if(p)page(p.dataset.page);let o=e.target.closest("[data-open]");if(o)openCareer(o.dataset.open);let s=e.target.closest("[data-save]");if(s)career(s.dataset.save)});
document.addEventListener("change",e=>{if(e.target.matches(".topic input"))topic(e.target.dataset.s,e.target.dataset.t,e.target.checked)});
$("authButton").onclick=()=>user?logout():page("auth");
async function boot(){if(!ready)$("setupNotice").classList.remove("hidden");if(!db)return page("auth");let s=await db.auth.getSession();if(s.data.session){user=s.data.session.user;try{await load();await achievements();$("accountLabel").textContent=profile.display_name||user.email;$("authButton").textContent="Log out";page(location.hash.slice(1)||"dashboard")}catch(e){msg(e.message)}}else page("auth");db.auth.onAuthStateChange((_e,s)=>{if(!s){user=null;$("accountLabel").textContent="Not signed in";$("authButton").textContent="Sign in"}})}
boot();